"""
session_manager.py
------------------
Core session management for TesseractRAG.

Contains:
    - SessionState  : In-memory representation of a single RAG session
    - SessionManager: Registry that creates, retrieves, lists, and deletes sessions

Storage backend: Cloudflare R2 (replaces local disk).
All persistence goes through R2Storage — no direct filesystem I/O here.
FAISS indexes are serialized to/from bytes via io.BytesIO for R2 transport.

Owner Identity (v1.1):
    Each session is tied to an owner_id — a random UUID generated by the
    browser on first visit and stored in localStorage. It is sent as the
    X-Owner-ID header on every request.

    This gives each browser a stable anonymous identity without requiring
    any login or database of users. Sessions created by owner A are
    invisible to owner B.

    Weakness: clearing localStorage loses the owner_id and therefore
    access to all owned sessions. Acceptable for a free-tier portfolio
    project. A future JWT auth layer would replace this.
"""

import io
import json
import faiss
from typing import Optional, Any
from datetime import datetime, timezone
from uuid import uuid4
import hashlib
import numpy as np


from fastapi import HTTPException

from app.models.session import SessionResponse
from app.config import get_settings as _config
from app.utils.logger import get_logger
from app.core.storage.r2_storage import R2Storage

from app.core.ingestion.parser import DocumentParser
from app.core.ingestion.chunker import RecursiveChunker
from app.core.ingestion.indexer import FAISSIndexer
from app.core.ingestion.embedder import Embedder
from app.core.retrieval.bm25_retriever import BM25Retriever

logger = get_logger(__name__)


# ── SessionState ───────────────────────────────────────────────────────────────

class SessionState:
    """
    In-memory representation of a single chat session.

    Holds all state for one isolated RAG environment:
    - Core identity  : id, name, description, created_at, owner_id
    - Document data  : document_names, chunks
    - ML indexes     : faiss_index, bm25_retriever
    - Conversation   : messages
    - R2 keys        : computed properties used as object keys in R2

    owner_id:
        A UUID string generated by the browser on first visit and stored
        in localStorage. Sent as X-Owner-ID on every request. Sessions
        are filtered and access-controlled by this value. It is persisted
        in metadata.json so ownership survives backend restarts.
    """

    def __init__(
        self,
        id: str,
        name: str,
        description: Optional[str],
        created_at: datetime,
        owner_id: str,                  # ← NEW: anonymous browser identity
    ):
        # Core identity — set at creation, never changed
        self.id = id
        self.name = name
        self.description = description
        self.created_at = created_at
        self.owner_id = owner_id        # ← NEW

        # Document data — populated during ingestion
        self.document_names: list[str] = []
        self.chunks: list[dict] = []

        # ML indexes — not JSON-serializable, rebuilt from R2 on startup
        self.faiss_index: Any = None
        self.bm25_retriever: Any = None

        # Conversation history
        self.messages: list[dict] = []

    # ── R2 key properties ──────────────────────────────────────────────────────

    @property
    def r2_prefix(self) -> str:
        """Root prefix for all R2 objects belonging to this session."""
        return f"sessions/{self.id}"

    @property
    def r2_metadata_key(self) -> str:
        return f"{self.r2_prefix}/metadata.json"

    @property
    def r2_chunks_key(self) -> str:
        return f"{self.r2_prefix}/chunks.json"

    @property
    def r2_index_key(self) -> str:
        return f"{self.r2_prefix}/faiss.index"

    def __repr__(self) -> str:
        return (
            f"SessionState(id={self.id!r}, name={self.name!r}, "
            f"owner={self.owner_id[:8]}..., "
            f"docs={len(self.document_names)}, chunks={len(self.chunks)})"
        )


# ── SessionManager ─────────────────────────────────────────────────────────────

class SessionManager:
    """
    Registry for all active sessions.

    Responsibilities:
    - Create sessions with an owner_id and persist metadata to R2
    - Load persisted sessions from R2 on startup
    - Retrieve, list, and delete sessions — all filtered by owner_id
    - Enforce session isolation (each session has its own indexes)
    - Enforce ownership isolation (each owner sees only their sessions)

    Used as a singleton via get_session_manager() in dependencies.py.

    Owner isolation pattern:
        Every public method that accepts owner_id will raise HTTP 403
        if the requesting owner does not match the session's stored
        owner_id. This prevents one browser from accessing another
        browser's sessions even if it somehow knows the session UUID.
    """

    def __init__(self):
        # In-memory store: session_id → SessionState
        self._sessions: dict[str, SessionState] = {}

        # R2 client — single instance shared across all operations
        self._r2 = R2Storage()

        # Reload all sessions persisted from previous backend runs
        self._load_persisted_sessions()

    # ── Private helpers ────────────────────────────────────────────────────────

    def _save_metadata(self, session: SessionState) -> None:
        """
        Persist session metadata to R2 as JSON.

        Saves: id, name, description, created_at, owner_id,
               document_names, messages.
        Does NOT save faiss_index or bm25_retriever — they are binary ML
        objects. FAISS is saved separately as bytes; BM25 is rebuilt from chunks.

        Args:
            session: The SessionState object to persist.
        """
        data_dict = {
            "id":             session.id,
            "name":           session.name,
            "description":    session.description,
            "created_at":     session.created_at.isoformat(),
            "owner_id":       session.owner_id,       # ← NEW: persisted to R2
            "document_names": session.document_names,
            "messages":       session.messages,
        }
        self._r2.put_json(session.r2_metadata_key, data_dict)

    def _save_faiss_index(self, session: SessionState) -> None:
        """
        Serialize FAISS index to bytes and upload to R2.

        Why io.BytesIO?
            FAISS's save API writes to a file path on disk.
            We can't give it a file path for R2 — we need raw bytes.
            BytesIO acts as an in-memory file: FAISS writes into it,
            we read the bytes out and send them to R2.

        Args:
            session: SessionState containing a non-None faiss_index.
        """
        buf = io.BytesIO()
        faiss.write_index(
            session.faiss_index.index,
            faiss.PyCallbackIOWriter(buf.write),
        )
        buf.seek(0)
        self._r2.put(session.r2_index_key, buf.read())

    def _load_faiss_index(self, session: SessionState, dimension: int) -> Optional[FAISSIndexer]:
        """
        Download FAISS bytes from R2 and deserialize into a FAISSIndexer.

        Args:
            session:   SessionState to load the index for.
            dimension: Embedding dimension (must match what was used at index time).

        Returns:
            Populated FAISSIndexer, or None if no index exists in R2 yet.
        """
        raw = self._r2.get(session.r2_index_key)
        if raw is None:
            return None

        buf = io.BytesIO(raw)
        raw_index = faiss.read_index(
            faiss.PyCallbackIOReader(buf.read)
        )

        indexer = FAISSIndexer(dimension)
        indexer.index = raw_index
        return indexer

    def _load_persisted_sessions(self) -> None:
        """
        Reload all sessions persisted to R2 on startup.

        For each session ID found in R2:
          1. Load metadata.json → rebuild SessionState (including owner_id)
          2. Load chunks.json   → restore session.chunks
          3. Load faiss.index   → rebuild FAISSIndexer from bytes
          4. Rebuild BM25 from chunks (BM25 is not stored — it's fast to rebuild)
          5. Add to self._sessions

        Sessions created before owner_id was introduced will have no owner_id
        in their metadata.json. These are loaded with owner_id="legacy" so
        they remain accessible rather than being silently dropped. In a
        production system you would migrate these — for a portfolio project
        this is acceptable.

        Any session with a missing or corrupt metadata.json is skipped with
        a warning rather than crashing the entire startup.
        """
        session_ids = self._r2.list_session_ids()

        loaded = 0
        for session_id in session_ids:
            try:
                # 1. Load metadata
                meta = self._r2.get_json(f"sessions/{session_id}/metadata.json")
                if meta is None:
                    logger.warning(f"Session {session_id[:8]}... has no metadata, skipping")
                    continue

                session = SessionState(
                    id=meta["id"],
                    name=meta["name"],
                    description=meta["description"],
                    created_at=datetime.fromisoformat(meta["created_at"]),
                    # Graceful fallback for sessions created before v1.1
                    owner_id=meta.get("owner_id", "legacy"),  # ← NEW
                )
                session.document_names = meta.get("document_names", [])
                session.messages = meta.get("messages", [])

                # 2. Load chunks
                chunks = self._r2.get_json(session.r2_chunks_key)
                if chunks:
                    session.chunks = chunks

                    # 3. Load FAISS index from bytes
                    session.faiss_index = self._load_faiss_index(
                        session, _config().DIM_FAISS
                    )

                    # 4. Rebuild BM25 (fast, no storage needed)
                    session.bm25_retriever = BM25Retriever()
                    session.bm25_retriever.build(session.chunks)

                self._sessions[session.id] = session
                loaded += 1

            except Exception as e:
                logger.error(f"Failed to reload session {session_id[:8]}...: {e}")
                continue

        logger.info(f"Reloaded {loaded} session(s) from R2")

    def _assert_owner(self, session: SessionState, owner_id: str) -> None:
        """
        Raise HTTP 403 if owner_id does not match the session's owner.

        This is the single enforcement point for ownership. Every public
        method calls this before returning or mutating any session data.

        Args:
            session:  The SessionState to check.
            owner_id: The owner_id from the incoming request header.

        Raises:
            HTTPException 403: If ownership does not match.
        """
        if session.owner_id != owner_id:
            raise HTTPException(
                status_code=403,
                detail="Access denied: this session belongs to a different owner.",
            )

    # ── Public CRUD methods ────────────────────────────────────────────────────

    def create_session(
        self,
        name: str,
        description: Optional[str],
        owner_id: str,                  # ← NEW
    ) -> SessionResponse:
        """
        Create a new session, persist it to R2, and return its response model.

        Args:
            name:        Display name for the session.
            description: Optional description.
            owner_id:    Anonymous browser UUID from X-Owner-ID header.

        Returns:
            SessionResponse with all session metadata.
        """
        session_id = str(uuid4())

        session = SessionState(
            id=session_id,
            name=name,
            description=description,
            created_at=datetime.now(timezone.utc),
            owner_id=owner_id,          # ← NEW
        )

        self._sessions[session_id] = session
        self._save_metadata(session)

        logger.info(
            f"Created session {session_id[:8]}... | "
            f"name='{name}' | owner={owner_id[:8]}..."
        )

        return SessionResponse(
            id=session.id,
            name=session.name,
            description=session.description,
            created_at=session.created_at,
            document_count=len(session.document_names),
            message_count=len(session.messages),
        )

    def get_session(self, session_id: str, owner_id: Optional[str] = None) -> SessionState:
        """
        Retrieve a session by ID, optionally enforcing ownership.

        owner_id is Optional here to support internal calls (e.g. startup
        reload) that don't have an owner context. All external API calls
        must pass owner_id.

        Args:
            session_id: UUID of the session.
            owner_id:   If provided, raises 403 if it doesn't match.

        Raises:
            HTTPException 404: If session_id is not found.
            HTTPException 403: If owner_id is provided and doesn't match.
        """
        if session_id not in self._sessions:
            raise HTTPException(status_code=404, detail="Session not found")

        session = self._sessions[session_id]

        if owner_id is not None:
            self._assert_owner(session, owner_id)

        return session

    def list_sessions(self, owner_id: str) -> list[SessionResponse]:
        """
        Return a SessionResponse for every session owned by owner_id.

        Sessions belonging to other owners are not included — they are
        completely invisible to this call.

        Args:
            owner_id: Anonymous browser UUID from X-Owner-ID header.

        Returns:
            List of SessionResponse objects, may be empty.
        """
        return [
            SessionResponse(
                id=s.id,
                name=s.name,
                description=s.description,
                created_at=s.created_at,
                document_count=len(s.document_names),
                message_count=len(s.messages),
            )
            for s in self._sessions.values()
            if s.owner_id == owner_id   # ← filter by owner
        ]

    def delete_session(self, session_id: str, owner_id: str) -> None:   # ← NEW param
        """
        Delete a session from memory and remove all its R2 objects.

        Enforces ownership — only the session's owner can delete it.
        Order: remove from R2 first, then from memory.
        If R2 deletion fails, the session remains in memory (no orphaned state).

        Args:
            session_id: UUID of the session to delete.
            owner_id:   Must match session.owner_id or raises 403.

        Raises:
            HTTPException 404: If session_id is not found.
            HTTPException 403: If owner_id does not match.
        """
        session = self.get_session(session_id, owner_id=owner_id)   # ← ownership enforced
        self._r2.delete_prefix(f"{session.r2_prefix}/")
        del self._sessions[session_id]
        logger.info(f"Deleted session {session_id[:8]}... | owner={owner_id[:8]}...")

    def add_message(
        self,
        session_id: str,
        role: str,
        content: str,
        owner_id: str,              # ← NEW
    ) -> None:
        """
        Append a message to conversation history and persist to R2.

        Args:
            session_id: UUID of the session.
            role:       "user" or "assistant".
            content:    The message text.
            owner_id:   Must match session.owner_id or raises 403.

        Raises:
            HTTPException 404: If session_id is not found.
            HTTPException 403: If owner_id does not match.
        """
        session = self.get_session(session_id, owner_id=owner_id)   # ← ownership enforced

        session.messages.append({
            "role":      role,
            "content":   content,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

        self._save_metadata(session)
        logger.info(f"Message saved | session={session_id[:8]}... | role={role}")

    def delete_document(self, session: SessionState, filename: str, owner_id: str) -> int:
        """
        Remove all chunks belonging to filename, rebuild FAISS + BM25,
        and persist updated state to R2.
        """
        self._assert_owner(session, owner_id)

        # 1. Filter chunks
        original_count = len(session.chunks)
        session.chunks = [c for c in session.chunks if c["document_name"] != filename]
        removed_count = original_count - len(session.chunks)

        if removed_count == 0:
            return 0

        # 2. Update document_names
        session.document_names = [n for n in session.document_names if n != filename]

        # 3. Persist updated chunks to R2
        self._r2.put_json(session.r2_chunks_key, session.chunks)

        # 4. Rebuild + persist FAISS (using your existing _save_faiss_index)
        if session.chunks:
            vectors = np.array(
                [c["embedding"] for c in session.chunks], dtype=np.float32
            )
            session.faiss_index = FAISSIndexer(_config().DIM_FAISS)
            session.faiss_index.index.add(vectors)
            self._save_faiss_index(session)   # ← your existing method
        else:
            session.faiss_index = None

        # 5. Rebuild BM25 in memory (never persisted — same as startup path)
        if session.chunks:
            session.bm25_retriever = BM25Retriever()
            session.bm25_retriever.build(session.chunks)
        else:
            session.bm25_retriever = None

        # 6. Persist updated metadata (uses your existing _save_metadata)
        self._save_metadata(session)          # ← your existing method

        return removed_count

    def ingest_document(
        self,
        session_id: str,
        file_bytes: bytes,
        filename: str,
        owner_id: str,   # ← NEW
    ) -> int:
        """
        Run the full ingestion pipeline for one document.

        Steps:
            1. Parse document → raw text
            2. Chunk text → list of chunk dicts
            3. Embed chunks → float32 vectors
            4. Add vectors to FAISS index (create if first document)
            5. Extend session.chunks
            6. Rebuild BM25 over all session chunks
            7. Append filename to session.document_names
            8. Persist: FAISS bytes → R2, chunks JSON → R2, metadata → R2

        Args:
            session_id: UUID of the target session.
            file_bytes: Raw file content as bytes.
            filename:   Original filename (used for chunk attribution).
            owner_id:   Must match session.owner_id or raises 403.

        Returns:
            Number of chunks created from this document.

        Raises:
            HTTPException 400: If the file type is unsupported.
            HTTPException 403: If owner_id does not match.
            HTTPException 404: If the session is not found.
        """
        session = self.get_session(session_id, owner_id=owner_id)   # ← ownership enforced

        # 1. Parse
        try:
            doc = DocumentParser().parse(file_bytes, filename)
        except ValueError as e:
            raise HTTPException(status_code=400, detail=str(e))

        # 2. Chunk
        chunks = RecursiveChunker(
            chunk_size=_config().CHUNK_SIZE,
            chunk_overlap=_config().CHUNK_OVERLAP,
        ).split(doc, filename)

        # 3. Embed
        vectors = Embedder().embed_chunks(chunks=chunks)

        # ── ADD THIS ──────────────────────────────────────────────────────────
        # Store each vector inside its chunk dict so chunks.json is self-contained.
        # This makes FAISS rebuild on delete instant (no re-embedding needed).
        for i, chunk in enumerate(chunks):
            chunk["embedding"] = vectors[i].tolist()   # float32 → JSON-serializable list
        # ─────────────────────────────────────────────────────────────────────

        # 4. Add to FAISS (create index on first document)
        if session.faiss_index is None:
            session.faiss_index = FAISSIndexer(vectors.shape[1])
        session.faiss_index.add(vectors)

        # 5. Extend chunk list  ← now chunks carry their embeddings
        session.chunks.extend(chunks)
        # 6. Rebuild BM25 over all chunks
        session.bm25_retriever = BM25Retriever()
        session.bm25_retriever.build(session.chunks)

        # 7. Record filename
        session.document_names.append(filename)

        # 8. Persist everything to R2
        self._save_faiss_index(session)
        self._r2.put_json(session.r2_chunks_key, session.chunks)
        self._save_metadata(session)

        logger.info(
            f"Ingested '{filename}' | session={session_id[:8]}... "
            f"| owner={owner_id[:8]}... "
            f"| chunks={len(chunks)} | total={len(session.chunks)}"
        )
        return len(chunks)
